version: '2'
services:
    hipster3-app:
        image: hipster3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hipster3-postgresql:5432/hipster3
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hipster3-postgresql:
        extends:
            file: postgresql.yml
            service: hipster3-postgresql
